language: python
python:
  - "3.5"

services: postgresql

install:
  - pip install -r pip-requirements.txt
  - pip install coverage
  - psql -c "CREATE DATABASE bocabit_code;" -U postgres

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script: coverage run manage.py test

after_success: coverage report