language: python
python:
  - "3.5"

services: postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage
  - psql -c "CREATE DATABASE bocabit_code;" -U postgres

before_script:
  - cd web
  - mv ./codeproject/config.sample.py ./codeproject/config.py
  - python manage.py makemigrations
  - python manage.py migrate

script: coverage run --source='.' manage.py test

after_success: coverage report