"""
Django settings for codeproject project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from codeproject import config

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gj=s&5+4z3_-1l9li-d52mdybk6r)vct@!-%vzm_-fo((*er3d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.DEBUG

ALLOWED_HOSTS = config.ALLOWED_HOSTS

# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Application
    'users.apps.UsersConfig',
    'codeapp.apps.CodeappConfig',
    # 3rd party
    'django_assets',
    'formtools',
    'social_django',
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend'
)

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'social_core.pipeline.social_auth.associate_by_email',
    'codeproject.pipeline.get_avatar'
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codeproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]

WSGI_APPLICATION = 'codeproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s | %(asctime)s | %(name)s | %(module)s | %(funcName)s():%(lineno)d :  %(message)s'
            # 'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s',
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': config.LOG_DEBUG_PATH,
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',  # DEBUG displays db queries
            'propagate': True,
        },
        'webapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG'
        }
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

ASSETS_ROOT = 'codeapp'
ASSETS_URL = ''

AUTH_USER_MODEL = 'users.User'

LANGUAGE_CHOICES = (('abap', 'ABAP'),
                    ('actionscript', 'ActionScript'),
                    ('ada', 'ADA'),
                    ('apache_conf', 'Apache Conf'),
                    ('asciidoc', 'AsciiDoc'),
                    ('assembly_x86', 'Assembly x86'),
                    ('autohotkey', 'AutoHotKey'),
                    ('batchfile', 'BatchFile'),
                    ('c9search', 'C9Search'),
                    ('c_cpp', 'C/C++'),
                    ('cirru', 'Cirru'),
                    ('clojure', 'Clojure'),
                    ('cobol', 'Cobol'),
                    ('coffee', 'CoffeeScript'),
                    ('coldfusion', 'ColdFusion'),
                    ('csharp', 'C#'),
                    ('css', 'CSS'),
                    ('curly', 'Curly'),
                    ('d', 'D'),
                    ('dart', 'Dart'),
                    ('diff', 'Diff'),
                    ('dot', 'Dot'),
                    ('erlang', 'Erlang'),
                    ('ejs', 'EJS'),
                    ('forth', 'Forth'),
                    ('ftl', 'FreeMarker'),
                    ('gherkin', 'Gherkin'),
                    ('glsl', 'Glsl'),
                    ('golang', 'Go'),
                    ('groovy', 'Groovy'),
                    ('haml', 'HAML'),
                    ('handlebars', 'Handlebars'),
                    ('haskell', 'Haskell'),
                    ('haxe', 'haXe'),
                    ('html', 'HTML'),
                    ('html_ruby', 'HTML (Ruby)'),
                    ('ini', 'INI'),
                    ('jack', 'Jack'),
                    ('jade', 'Jade'),
                    ('java', 'Java'),
                    ('javascript', 'JavaScript'),
                    ('json', 'JSON'),
                    ('jsoniq', 'JSONiq'),
                    ('jsp', 'JSP'),
                    ('jsx', 'JSX'),
                    ('julia', 'Julia'),
                    ('latex', 'LaTeX'),
                    ('less', 'LESS'),
                    ('liquid', 'Liquid'),
                    ('lisp', 'Lisp'),
                    ('livescript', 'LiveScript'),
                    ('logiql', 'LogiQL'),
                    ('lsl', 'LSL'),
                    ('lua', 'Lua'),
                    ('luapage', 'LuaPage'),
                    ('lucene', 'Lucene'),
                    ('makefile', 'Makefile'),
                    ('matlab', 'MATLAB'),
                    ('markdown', 'Markdown'),
                    ('mel', 'MEL'),
                    ('mysql', 'MySQL'),
                    ('mushcode', 'MUSHCode'),
                    ('nix', 'Nix'),
                    ('objectivec', 'Objective-C'),
                    ('ocaml', 'OCaml'),
                    ('pascal', 'Pascal'),
                    ('perl', 'Perl'),
                    ('pgsql', 'pgSQL'),
                    ('php', 'PHP'),
                    ('powershell', 'Powershell'),
                    ('prolog', 'Prolog'),
                    ('properties', 'Properties'),
                    ('protobuf', 'Protobuf'),
                    ('python', 'Python'),
                    ('r', 'R'),
                    ('rdoc', 'RDoc'),
                    ('rhtml', 'RHTML'),
                    ('ruby', 'Ruby'),
                    ('rust', 'Rust'),
                    ('sass', 'SASS'),
                    ('scad', 'SCAD'),
                    ('scala', 'Scala'),
                    ('smarty', 'Smarty'),
                    ('scheme', 'Scheme'),
                    ('scss', 'SCSS'),
                    ('sh', 'SH'),
                    ('sjs', 'SJS'),
                    ('space', 'Space'),
                    ('snippets', 'snippets'),
                    ('soy_template', 'Soy Template'),
                    ('sql', 'SQL'),
                    ('stylus', 'Stylus'),
                    ('svg', 'SVG'),
                    ('tcl', 'Tcl'),
                    ('tex', 'Tex'),
                    ('text', 'Text'),
                    ('textile', 'Textile'),
                    ('toml', 'Toml'),
                    ('twig', 'Twig'),
                    ('typescript', 'Typescript'),
                    ('vbscript', 'VBScript'),
                    ('velocity', 'Velocity'),
                    ('verilog', 'Verilog'),
                    ('xml', 'XML'),
                    ('xquery', 'XQuery'),
                    ('yaml', 'YAML'),)
