# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='codes', to='codeapp.Tag')),
                ('workspaces', models.ManyToManyField(blank=True, related_name='codes', to='codeapp.Workspace')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='workspaces',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('title', 'owner')]),
        ),
    ]
