# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_auto_20171109_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
