# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeapp', '0003_auto_20171109_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('abap', 'ABAP'), ('actionscript', 'ActionScript'), ('ada', 'ADA'), ('apache_conf', 'Apache Conf'), ('asciidoc', 'AsciiDoc'), ('assembly_x86', 'Assembly x86'), ('autohotkey', 'AutoHotKey'), ('batchfile', 'BatchFile'), ('c9search', 'C9Search'), ('c_cpp', 'C/C++'), ('cirru', 'Cirru'), ('clojure', 'Clojure'), ('cobol', 'Cobol'), ('coffee', 'CoffeeScript'), ('coldfusion', 'ColdFusion'), ('csharp', 'C#'), ('css', 'CSS'), ('curly', 'Curly'), ('d', 'D'), ('dart', 'Dart'), ('diff', 'Diff'), ('dot', 'Dot'), ('erlang', 'Erlang'), ('ejs', 'EJS'), ('forth', 'Forth'), ('ftl', 'FreeMarker'), ('gherkin', 'Gherkin'), ('glsl', 'Glsl'), ('golang', 'Go'), ('groovy', 'Groovy'), ('haml', 'HAML'), ('handlebars', 'Handlebars'), ('haskell', 'Haskell'), ('haxe', 'haXe'), ('html', 'HTML'), ('html_ruby', 'HTML (Ruby)'), ('ini', 'INI'), ('jack', 'Jack'), ('jade', 'Jade'), ('java', 'Java'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('jsoniq', 'JSONiq'), ('jsp', 'JSP'), ('jsx', 'JSX'), ('julia', 'Julia'), ('latex', 'LaTeX'), ('less', 'LESS'), ('liquid', 'Liquid'), ('lisp', 'Lisp'), ('livescript', 'LiveScript'), ('logiql', 'LogiQL'), ('lsl', 'LSL'), ('lua', 'Lua'), ('luapage', 'LuaPage'), ('lucene', 'Lucene'), ('makefile', 'Makefile'), ('matlab', 'MATLAB'), ('markdown', 'Markdown'), ('mel', 'MEL'), ('mysql', 'MySQL'), ('mushcode', 'MUSHCode'), ('nix', 'Nix'), ('objectivec', 'Objective-C'), ('ocaml', 'OCaml'), ('pascal', 'Pascal'), ('perl', 'Perl'), ('pgsql', 'pgSQL'), ('php', 'PHP'), ('powershell', 'Powershell'), ('prolog', 'Prolog'), ('properties', 'Properties'), ('protobuf', 'Protobuf'), ('python', 'Python'), ('r', 'R'), ('rdoc', 'RDoc'), ('rhtml', 'RHTML'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('sass', 'SASS'), ('scad', 'SCAD'), ('scala', 'Scala'), ('smarty', 'Smarty'), ('scheme', 'Scheme'), ('scss', 'SCSS'), ('sh', 'SH'), ('sjs', 'SJS'), ('space', 'Space'), ('snippets', 'snippets'), ('soy_template', 'Soy Template'), ('sql', 'SQL'), ('stylus', 'Stylus'), ('svg', 'SVG'), ('tcl', 'Tcl'), ('tex', 'Tex'), ('text', 'Text'), ('textile', 'Textile'), ('toml', 'Toml'), ('twig', 'Twig'), ('typescript', 'Typescript'), ('vbscript', 'VBScript'), ('velocity', 'Velocity'), ('verilog', 'Verilog'), ('xml', 'XML'), ('xquery', 'XQuery'), ('yaml', 'YAML')], max_length=100)),
                ('version_number', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_snippets', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='codeapp.Code')),
            ],
            options={
                'abstract': False,
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('abap', 'ABAP'), ('actionscript', 'ActionScript'), ('ada', 'ADA'), ('apache_conf', 'Apache Conf'), ('asciidoc', 'AsciiDoc'), ('assembly_x86', 'Assembly x86'), ('autohotkey', 'AutoHotKey'), ('batchfile', 'BatchFile'), ('c9search', 'C9Search'), ('c_cpp', 'C/C++'), ('cirru', 'Cirru'), ('clojure', 'Clojure'), ('cobol', 'Cobol'), ('coffee', 'CoffeeScript'), ('coldfusion', 'ColdFusion'), ('csharp', 'C#'), ('css', 'CSS'), ('curly', 'Curly'), ('d', 'D'), ('dart', 'Dart'), ('diff', 'Diff'), ('dot', 'Dot'), ('erlang', 'Erlang'), ('ejs', 'EJS'), ('forth', 'Forth'), ('ftl', 'FreeMarker'), ('gherkin', 'Gherkin'), ('glsl', 'Glsl'), ('golang', 'Go'), ('groovy', 'Groovy'), ('haml', 'HAML'), ('handlebars', 'Handlebars'), ('haskell', 'Haskell'), ('haxe', 'haXe'), ('html', 'HTML'), ('html_ruby', 'HTML (Ruby)'), ('ini', 'INI'), ('jack', 'Jack'), ('jade', 'Jade'), ('java', 'Java'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('jsoniq', 'JSONiq'), ('jsp', 'JSP'), ('jsx', 'JSX'), ('julia', 'Julia'), ('latex', 'LaTeX'), ('less', 'LESS'), ('liquid', 'Liquid'), ('lisp', 'Lisp'), ('livescript', 'LiveScript'), ('logiql', 'LogiQL'), ('lsl', 'LSL'), ('lua', 'Lua'), ('luapage', 'LuaPage'), ('lucene', 'Lucene'), ('makefile', 'Makefile'), ('matlab', 'MATLAB'), ('markdown', 'Markdown'), ('mel', 'MEL'), ('mysql', 'MySQL'), ('mushcode', 'MUSHCode'), ('nix', 'Nix'), ('objectivec', 'Objective-C'), ('ocaml', 'OCaml'), ('pascal', 'Pascal'), ('perl', 'Perl'), ('pgsql', 'pgSQL'), ('php', 'PHP'), ('powershell', 'Powershell'), ('prolog', 'Prolog'), ('properties', 'Properties'), ('protobuf', 'Protobuf'), ('python', 'Python'), ('r', 'R'), ('rdoc', 'RDoc'), ('rhtml', 'RHTML'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('sass', 'SASS'), ('scad', 'SCAD'), ('scala', 'Scala'), ('smarty', 'Smarty'), ('scheme', 'Scheme'), ('scss', 'SCSS'), ('sh', 'SH'), ('sjs', 'SJS'), ('space', 'Space'), ('snippets', 'snippets'), ('soy_template', 'Soy Template'), ('sql', 'SQL'), ('stylus', 'Stylus'), ('svg', 'SVG'), ('tcl', 'Tcl'), ('tex', 'Tex'), ('text', 'Text'), ('textile', 'Textile'), ('toml', 'Toml'), ('twig', 'Twig'), ('typescript', 'Typescript'), ('vbscript', 'VBScript'), ('velocity', 'Velocity'), ('verilog', 'Verilog'), ('xml', 'XML'), ('xquery', 'XQuery'), ('yaml', 'YAML')], max_length=100)),
                ('version_number', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_versions', to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='codeapp.Snippet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('snippet', 'version_number')]),
        ),
    ]
