# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeapp', '0005_auto_20171110_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='code',
            name='workspaces',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
        migrations.AddField(
            model_name='code',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='codes', to='codeapp.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('title', 'owner')]),
        ),
    ]
